language: minimal

services:
- docker

before_install:
- docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit --exit-code-from app

branches:
  only:
  - main

notifications:
  email:
    recipients:
    - danilarassokhin@gmail.com
    on_success: never
    on_failure: always